### ISSUE TITLE
tuya-panel-demo/examples/ipcBasic 全屏播放错误

### ISSUE THREAD

**Issue by 1004634740** [tuya/tuya-panel-sdk#17]
## 组件

组件名称 
tuya-panel-demo/examples/ipcBasic/

## 版本

- 组件版本：
- react 版本：
- react-native 版本：

## 概述

Bug 问题概述 
IPC点击全屏播放时报错

## 重现步骤
IPC连接成功后，点击全屏，直接报错

## Bug 行为

Bug 的表现行为

## 期望行为

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志
![image](https://user-images.githubusercontent.com/54577520/104413174-d1f08680-55a8-11eb-8a82-959eb5b9096f.png)

**Comment by 1004634740** [comment]
手机版本：红米note7

**Comment by 1004634740** [comment]
手机：红米note7
APP：涂鸦智能Debug版
版本号：3.23.5

**Comment by youngjuning** [comment]
@1004634740 @tuya-smart/tuya-panel-ipc-sdk@1.0.3 已修复
