### ISSUE TITLE
Unable to use ipc player

### ISSUE THREAD

**Issue by shrynshjn** [tuya/tuya-panel-sdk#75]
Hi,
I am trying to use the tuya IPC panel SDK, the typlayer but am unable to configure it.
How do I specify which device (camera) should the player try to connect to, the documentation isn't clear and I can't find a way to configure the player to open my stream.
I used volst/react-native-tuya instead of the tuyasmart-home-sdk-react-native, as the documentation of the latter one wasn't really helpful either.
I want to use tuya cameras in my app and any help will be appreciated. If any data is required from my side, I will be happy to provide it

**Comment by youngjuning** [comment]
@xiaaa123 @XiaooSe

**Comment by shrynshjn** [comment]
Hi, any updates regarding this?

**Comment by youngjuning** [comment]
> Hi, any updates regarding this?

@XiaooSe working on it now.

**Comment by XiaooSe** [comment]
Hi！Thanks for your question.

Here are some reference documents, I hope to help you

1. Ipc panel Demo address: https://github.com/tuya/tuya-panel-demo/tree/master/examples/ipcBasic
    You can scan the QR code in the readme to browse the demo.
2. Player component: https://developer.tuya.com/en/docs/control-panel-sdk/player?id=Ka7jox31piji2
3. Player control: https://developer.tuya.com/en/docs/control-panel-sdk/player-function-library?id=Ka5g8h2zx3fv8

You only need to import components in the panel.
It is recommended to use the demo we provide.

Hope my answer can help you！Looking forward to your feedback！

**Comment by shrynshjn** [comment]
Hi, the example is in react-native version 0.59, it is a pretty old react-native version, and lacks a lot of features that react-native > 0.6 provides. Are you people planning to make a demo that works in rn > 0.6 perhaps the latest version?

**Comment by XiaooSe** [comment]
Hi, Due to the unstable aspects of the version upgrade, it will not be supported in the near future！Please continue to pay attention
